package com.Features.FacultyAttendance.model;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * One QR code generated by admin per calendar date.
 * All faculty scan this same QR to mark their attendance for the day.
 *
 * The QR changes every day — admin generates it each morning,
 * or a scheduled task can auto-generate it at midnight.
 *
 * QR content = a URL:  https://yourdomain.com/faculty-attend?token=<tokenValue>
 */
@Entity
@Table(
    name = "faculty_daily_qr",
    uniqueConstraints = {
        @UniqueConstraint(name = "uk_faculty_qr_date", columnNames = {"qr_date"})
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class FacultyDailyQr {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(updatable = false, nullable = false)
    private UUID id;

    /** The calendar date this QR is valid for */
    @Column(name = "qr_date", nullable = false)
    private LocalDate qrDate;

    /** The random token encoded in the QR URL */
    @Column(name = "token_value", nullable = false, unique = true, length = 36)
    private String tokenValue;

    /** When this QR expires (usually end of business day) */
    @Column(name = "expires_at", nullable = false)
    private LocalDateTime expiresAt;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 10)
    @Builder.Default
    private FacultyQrStatus status = FacultyQrStatus.ACTIVE;

    /** Admin who generated this QR */
    @Column(name = "generated_by", length = 100)
    private String generatedBy;

    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;
}
