package com.Features.Student.controller;

import com.Features.Student.dto.StudentLoginRequest;
import com.Features.Student.dto.StudentLoginResponse;
import com.Features.Student.service.StudentAuthService;
import com.common.ApiResponse;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/auth/student")
@RequiredArgsConstructor
public class StudentAuthController {

    private final StudentAuthService studentAuthService;

    /**
     * POST /api/auth/student/login
     * Public — no JWT required.
     *
     * PHONE-FIRST RULE:
     *   If this is the student's first login AND the request is NOT from a mobile
     *   browser → 403 rejected. Student must log in from their phone first.
     *
     * DEVICE REGISTRATION:
     *   On first successful mobile login → deviceId (from X-Device-Id header) is
     *   saved to StudentAccount. The frontend must generate and persist this ID in
     *   localStorage, then send it with every request.
     *
     * DEVICE CHANGE (soft binding):
     *   If deviceId doesn't match the registered one → login succeeds BUT a
     *   DeviceChangeLog is created and admin receives an email alert.
     *
     * Request headers:
     *   User-Agent   — standard browser header (auto-sent)
     *   X-Device-Id  — UUID generated by frontend, stored in localStorage
     *
     * Request body:
     * {
     *   "email":    "student@college.com",
     *   "password": "john@3210"
     * }
     *
     * Response flags:
     *   phoneRegistered      — whether phone has ever been registered
     *   deviceJustRegistered — true on the exact login that registered the phone
     *   deviceChanged        — true if a different device was used this login
     */
    @PostMapping("/login")
    public ResponseEntity<ApiResponse<StudentLoginResponse>> login(
            @Valid @RequestBody StudentLoginRequest request,
            HttpServletRequest httpRequest) {

        String userAgent = httpRequest.getHeader("User-Agent");
        String deviceId  = httpRequest.getHeader("X-Device-Id");

        StudentLoginResponse data = studentAuthService.login(request, userAgent, deviceId);
        return ResponseEntity.ok(ApiResponse.success("Login successful", data));
    }
}
